---
Name: totpsecurity
After:
  - '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        totp: %$ElliotSawyer\TOTPAuthenticator\TOTPAuthenticator
ElliotSawyer\TOTPAuthenticator\TOTPLoginForm:
  authenticator_class: ElliotSawyer\TOTPAuthenticator\TOTPAuthenticator
